### PR TITLE
Accidentally merged the cromlech one into my own not the other way around here's the correct one

### PR DESCRIPTION
**Pull request by alFung**
Updated lab 0 readme

### CODE REVIEW

**Comment by crimtech** [comment]
Hey Alex! I don't see any changes (i.e., your lab 0 file text changes) in the commit. Did you make a PR on the commit that contains your changes to the lab 0 file?

**Comment by alFung** [comment]
Ok I see what you mean. The files I added are visible in my github page for
the branch I sent but they aren't on the pull request.

**Comment by alFung** [comment]
I am fixing it.

**Comment by alFung** [comment]
done

**Pull request closed without merging**
